apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    part: backend-user
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    part: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      part: backend-user
  template:
    metadata:
      labels:
        part: backend-user
    spec:
      containers:
      - name: superknife0512/uda-backend-user
        image: superknife0512/uda-backend-user
        ports:
        - containerPort: 5002