apiVersion: v1
kind: Service
metadata:
  name: backend-feed
spec:
  selector:
    part: backend-feed
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    part: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      part: backend-feed
  template:
    metadata:
      labels:
        part: backend-feed
    spec:
      containers:
      - name: superknife0512/uda-backend-feed
        image: superknife0512/uda-backend-feed
        ports:
        - containerPort: 5001