apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    part: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    part: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      part: frontend
  template:
    metadata:
      labels:
        part: frontend
    spec:
      containers:
      - name: uda-micro-frontend
        image: superknife0512/uda-micro-frontend
        ports:
        - containerPort: 80